import {useEffect,useState,type FormEvent} from 'react'
import {Cat,LogOut,Save,ShieldCheck,Plus,Trash2,RefreshCw} from 'lucide-react'
import {api,compact,feesTotal} from './api'
import {Captcha} from './Captcha'
import {UserManagement} from './Users'
import type {Market,Meta,Rules,Settings} from './types'

const fields:{key:keyof Rules;name:string;factor?:number;min:number;max:number;step?:number;hint:string}[]=[
  {key:'commissionPPM',name:'佣金率 (%)',factor:10000,min:0,max:100,step:.0001,hint:'每笔成交额的百分比'}, {key:'minCommission',name:'最低佣金 (模拟币)',factor:100,min:0,max:10000,step:.01,hint:'每笔佣金下限'},
  {key:'stampPPM',name:'印花税率 (%)',factor:10000,min:0,max:100,step:.0001,hint:'按下方征收方向'}, {key:'stampRound',name:'印花税向上取整 (模拟币)',factor:100,min:.01,max:100,step:.01,hint:'港股参考设为 1，其他通常为 0.01'},
  {key:'levyPPM',name:'交易征费率 (%)',factor:10000,min:0,max:100,step:.0001,hint:'双边额外成交费用'}, {key:'borrowAnnualPPM',name:'借券年费率 (%)',factor:10000,min:0,max:100,step:.01,hint:'按实际持仓时间计费'},
  {key:'financingAnnualPPM',name:'融资年利率 (%)',factor:10000,min:0,max:100,step:.01,hint:'按借款本金和实际持有时间计息'},
  {key:'imrPPM',name:'初始保证金 IMR (%)',factor:10000,min:10,max:200,step:.01,hint:'限制融资/卖空杠杆；另冻结全部做空所得'}, {key:'mmrPPM',name:'维持保证金 MMR (%)',factor:10000,min:5,max:200,step:.01,hint:'不可超过 IMR，杠杆持仓净值不足时强平'},
  {key:'lotSize',name:'整手单位 (股)',min:1,max:10000,hint:'所有委托数量须为此整数倍'}, {key:'sellDelayDays',name:'股份可卖延迟 (交易日)',min:0,max:5,hint:'买入后 T+N 可卖'},
  {key:'cashDelayDays',name:'现金可用延迟 (交易日)',min:0,max:5,hint:'卖出所得 T+N 可再投资'}, {key:'quoteTTLSeconds',name:'报价有效期 (秒)',min:60,max:604800,hint:'逾期报价暂停新成交'}
]
export function Console({meta}:{meta:Meta}){
  const [section,setSection]=useState('rules')
  const [token,setToken]=useState(()=>sessionStorage.getItem('mmex.admin')??''),[password,setPassword]=useState(''),[captcha,setCaptcha]=useState(''),[reset,setReset]=useState(0),[settings,setSettings]=useState<Settings>(),[market,setMarket]=useState<Market>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[newID,setNewID]=useState(''),[newName,setNewName]=useState('')
  async function load(){try{const [s,m]=await Promise.all([api<Settings>('/console/settings',undefined,token),api<Market>('/market')]);setSettings(s);setMarket(m);setError('')}catch(e){setError((e as Error).message);if((e as {status?:number}).status===401){setToken('');sessionStorage.removeItem('mmex.admin')}}}
  useEffect(()=>{if(token)void load()},[token])
  async function login(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await api<{token:string}>('/console/login',{password,turnstileToken:captcha});sessionStorage.setItem('mmex.admin',result.token);setToken(result.token);setPassword('')}catch(e){setError((e as Error).message);setReset(n=>n+1)}finally{setBusy(false)}}
  async function save(){if(!settings)return;setBusy(true);setError('');setMessage('');try{setSettings(await api<Settings>('/console/settings',settings,token,'PUT'));setMessage('配置已发布。初始资金用于新开户及下个赛季重置，当前账户余额不变；月赛日期从下月生效，费率和时段即时生效。')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  function update(key:keyof Rules,value:unknown){setSettings(s=>s?{...s,active:{...s.active,[key]:value}}:s)}
  if(!token)return <div className="console-login"><section className="auth-dialog"><div className="auth-brand"><span className="brand-icon"><Cat size={26}/></span><div><h1>交易所控制台</h1><span>MMEX ADMINISTRATION</span></div></div><h2>管理员登录</h2><p className="muted">管理员凭据由服务器环境变量配置。</p><form className="form-stack" onSubmit={login}><label>管理员密码<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><Captcha meta={meta} action="console-login" onToken={setCaptcha} reset={reset}/>{error&&<div className="inline-error" role="alert">{error}</div>}<button className="primary wide" disabled={busy||!captcha}><ShieldCheck size={16}/>验证并登录控制台</button><a className="muted" href="/">← 返回服务首页</a></form></section></div>
  return <div className="console"><header className="console-top"><a className="brand" href="/"><Cat size={27}/><strong>茗喵证券交易所 <small>控制台</small></strong></a><button onClick={()=>{setToken('');sessionStorage.removeItem('mmex.admin')}}><LogOut size={15}/>退出管理</button></header><main><div className="section-heading"><div><p className="eyebrow">EXCHANGE OPERATIONS</p><h1>{section==='rules'?'交易规则与市场管理':'用户管理'}</h1><p className="muted">{section==='rules'?'统一模拟币计价，所有规则由交易引擎验证。':'查看账户资料、资金、持仓及委托，核实身份并修改用户信息。'}</p></div>{section==='rules'&&<button className="primary" disabled={busy||!settings} onClick={()=>void save()}><Save size={16}/>发布配置</button>}</div><nav className="console-navigation" aria-label="控制台功能"><button aria-pressed={section==='rules'} className={section==='rules'?'active':''} onClick={()=>{setSection('rules');setMessage('')}}>交易规则与市场管理</button><button aria-pressed={section==='users'} className={section==='users'?'active':''} onClick={()=>{setSection('users');setMessage('')}}>用户管理</button></nav>{error&&<div className="error-banner" role="alert">{error}</div>}{message&&<div className="success-banner" role="status">{message}</div>}
    <div className="console-stats">{[['上市玩家',String(market?.participants??0)],['本赛季交易所收入',compact(market?feesTotal(market.season.revenue):0)],['累计交易所收入',compact(market?feesTotal(market.lifetimeRevenue):0)],['市场状态',settings?.paused?'暂停':market?.reason??'加载中']].map(v=><section className="panel" key={v[0]}><span>{v[0]}</span><strong>{v[1]}</strong></section>)}</div>
    {section==='rules'&&settings&&<><section className="panel padded"><div className="panel-title"><h3>市场预设</h3><button className="small-button" onClick={()=>void load()}><RefreshCw size={14}/>重新加载</button></div><div className="preset-grid">{settings.presets.map(r=><button key={r.id} className={settings.active.id===r.id?'active':''} onClick={()=>setSettings({...settings,active:structuredClone(r)})}><strong>{r.name}</strong><span>{r.description}</span><small>{r.lotSize} 股 / T+{r.sellDelayDays} 可卖 / {r.borrowAnnualPPM/10000}% 借券</small></button>)}</div><div className="preset-tools"><input aria-label="新预设标识" placeholder="新预设标识，如 custom-01" value={newID} onChange={e=>setNewID(e.target.value)}/><input aria-label="新预设名称" placeholder="新预设名称" value={newName} onChange={e=>setNewName(e.target.value)}/><button disabled={!newID||!newName} onClick={()=>{if(settings.presets.some(p=>p.id===newID)){setError('预设标识已存在');return};const r={...settings.active,id:newID,name:newName};setSettings({...settings,active:r,presets:[...settings.presets,r]});setNewID('');setNewName('')}}><Plus size={15}/>另存为预设</button><button onClick={()=>setSettings({...settings,presets:settings.presets.map(p=>p.id===settings.active.id?structuredClone(settings.active):p)})}>更新当前预设</button><button disabled={settings.presets.length<=1} onClick={()=>{const presets=settings.presets.filter(p=>p.id!==settings.active.id);setSettings({...settings,presets,active:structuredClone(presets[0])})}}><Trash2 size={14}/>删除预设</button></div><small className="muted">选择、修改和删除先保存在草稿中，点击「发布配置」后生效。</small></section>
    <section className="panel padded"><h3>当前规则 · {settings.active.name}</h3><div className="console-fields"><label>初始资金 (模拟币)<input aria-label="初始资金 (模拟币)" type="number" min={1} max={1000000000000} step={.01} value={settings.initialCash/100} onChange={e=>setSettings({...settings,initialCash:Math.round(Number(e.target.value)*100)})}/><small>默认 20,000,000；用于新开户及下个赛季，当前余额不变</small></label><label>预设名称<input value={settings.active.name} onChange={e=>update('name',e.target.value)}/></label><label>印花税征收方向<select value={settings.active.stampSide} onChange={e=>update('stampSide',e.target.value)}><option value="sell">卖出侧（卖出 / 卖空）</option><option value="both">买卖双方</option></select></label>{fields.map(f=><label key={f.key}>{f.name}<input type="number" min={f.min} max={f.max} step={f.step??1} value={Number(settings.active[f.key])/(f.factor??1)} onChange={e=>update(f.key,Math.round(Number(e.target.value)*(f.factor??1)))}/><small>{f.hint}</small></label>)}<label>市场时区<input value={settings.active.timezone} onChange={e=>update('timezone',e.target.value)} placeholder="Asia/Shanghai"/></label><label>交易时段<input value={settings.active.sessions.join(',')} onChange={e=>update('sessions',e.target.value.split(','))}/><small>HH:MM-HH:MM，多段用英文逗号分隔</small></label><label className="check"><input type="checkbox" checked={settings.active.weekdaysOnly} onChange={e=>update('weekdaysOnly',e.target.checked)}/>周末休市</label><label className="check"><input type="checkbox" checked={settings.paused} onChange={e=>setSettings({...settings,paused:e.target.checked})}/>暂停市场（仍执行风控和截止结算）</label><label>休市日期<textarea rows={3} value={settings.active.holidays.join(',')} onChange={e=>update('holidays',e.target.value?e.target.value.split(',').map(s=>s.trim()):[])}/><small>YYYY-MM-DD，用英文逗号分隔</small></label><label>预设说明<textarea rows={3} value={settings.active.description} onChange={e=>update('description',e.target.value)}/></label><label>参考来源 URL<input value={settings.active.source} onChange={e=>update('source',e.target.value)}/></label><label>每月开赛日<input type="number" min={1} max={20} value={settings.startDay} onChange={e=>setSettings({...settings,startDay:Number(e.target.value)})}/></label><label>截止距月末天数<input type="number" min={0} max={7} value={settings.endDaysFromLast} onChange={e=>setSettings({...settings,endDaysFromLast:Number(e.target.value)})}/><small>倒数第 5 日填 4；上海时间该日结束时截止</small></label></div></section></>}
    {section==='users'&&<UserManagement token={token} market={market} onUnauthorized={()=>{setToken('');sessionStorage.removeItem('mmex.admin')}} onChanged={()=>{void api<Market>('/market').then(setMarket).catch(e=>setError(e.message))}}/>}
    </main></div>
}
