export interface Fees {commission:number;stamp:number;levy:number;borrow:number;financing?:number}
export interface Rules {id:string;name:string;description:string;commissionPPM:number;minCommission:number;stampPPM:number;stampSide:string;stampRound:number;levyPPM:number;borrowAnnualPPM:number;financingAnnualPPM:number;imrPPM:number;mmrPPM:number;lotSize:number;sellDelayDays:number;cashDelayDays:number;timezone:string;sessions:string[];weekdaysOnly:boolean;holidays:string[];quoteTTLSeconds:number;source:string}
export interface Settings {initialCash:number;delistThreshold:number;active:Rules;presets:Rules[];startDay:number;endDaysFromLast:number;paused:boolean}
export interface Quote {price:number;previous:number;observedAt:number;uploadedAt:number}
export interface Stock {id:number;symbol:string;username:string;quote:Quote;stale:boolean;disabled:boolean;delisted:boolean;open:number}
export interface Season {id:string;startsAt:number;endsAt:number;settled:boolean;revenue:Fees}
export interface Rank {rank:number;playerId:number;username:string;equity:number;returnPPM:number}
export interface Market {initialCash?:number;delistThreshold:number;revision:number;serverTime:number;season:Season;rules:Rules;open:boolean;reason:string;stocks:Stock[];rankings:Rank[];lifetimeRevenue:Fees;participants:number}
export interface Position {stockId:number;quantity:number;cost:number;lots:{quantity:number;availableAt:number}[];borrowAt:number;loan:number;marginPPM:number}
export interface Order {id:number;clientId:string;stockId:number;side:string;kind:string;tif:string;quantity:number;limit:number;leverage:number;status:string;price:number;fees:Fees;createdAt:number;executedAt:number;expiresAt:number;reason:string;reserved:number;rules:Rules}
export interface Player {id:number;username:string;identityCode:string;cash:number;initialCash:number;quote:Quote;positions:Record<string,Position>;settlements:{amount:number;availableAt:number}[];orders:Order[];realized:number;fees:Fees;joinedAt:number;disabled:boolean;delisted:boolean;watchlist?:number[];binding:{key:string;instanceId:string;publicKey:string}|null}
export interface Account {player:Player;equity:number;available:number;frozen:number;shortLiability:number;initialMargin:number;maintenanceMargin:number;unsettled:number;borrowAccrued:number;financingDebt:number;financingAccrued:number;longMargin:number}
export interface AdminPlayerSummary {id:number;symbol:string;username:string;identityCode:string;cash:number;equity:number;available:number;joinedAt:number;disabled:boolean;delisted:boolean;stale:boolean;instanceId:string;positionCount:number;pendingOrders:number;quote:Quote}
export interface AdminPlayerList {players:AdminPlayerSummary[];total:number;page:number;pageSize:number;active:number;disabled:number}
export interface AdminPlayerUpdate {username?:string;password?:string;cashAdjustment?:number;expectedCash?:number;disabled?:boolean}
export interface Meta {name:string;domain:string;mock:boolean;allowedOrigins:string[];initialCash:number;noticeVersion:string}
export interface QuotePoint {time:number;price:number}
export interface SeasonResult {season:Season;rankings:Rank[]}
export interface Snapshot {actionPoints:number;observedAt:number;instance:string}
